from setuptools import setup, find_packages

setup(
    name='your_project_name',
    version='1.0.0',
    packages=find_packages(),
    install_requires=[
        "colorama",
"encode",
"Flask",
"frozenlist",
"gunicorn",
"h11",
"h2",
"hpack",
"httplib2",
"hyperframe",
"idna",
"itsdangerous",
"Jinja2",
"MarkupSafe",
"multidict",
"numpy",
"packaging",
"pandas",
"PyJWT",
"pyparsing",
"python-dateutil",
"python-dotenv",
"pytz",
"requests",
"requests-toolbelt",
"rfc3986",
"schedule",
"simplejson",
"six",
"twilio",
"tzdata",
"tzlocal",
"urllib3",
"Werkzeug",
"yarl",
"pypodio2 @ git+https://github.com/Derrick4822/Last.git",
"requests" # Private repository package
    ],
)